### ISSUE TITLE
Rework support

### ISSUE THREAD

**Issue by voronianski** [geddski/csstyle#13]
And as [Myth](http://www.myth.io/) is based on Rework it could be supported as well (hopefully).

**Comment by geddski** [comment]
@voronianski hmm maybe, it Myth doesn't appear to have mixins or custom functions, unless I'm missing something.

**Comment by geddski** [comment]
I've started on the rework port, but quickly realized rework doesn't support nested styles... not sure how this would work without that. I opened [an issue](https://github.com/reworkcss/rework/issues/184) on their repo.

**Comment by geddski** [comment]
@voronianski FYI I've added [postcss](https://github.com/postcss/postcss) support, which is very similar to [rework](https://github.com/reworkcss/rework). Closing this for now, can reconsider if rework ever adds nesting support.
