### ISSUE TITLE
Support for libsass

### ISSUE THREAD

**Issue by simonexmachina** [geddski/csstyle#19]
My build tool uses libsass, which doesn't seem to provide the features that are required by csstyle :( What version of SASS is required for csstyle? They're currently working on 3.0rc4, but I don't know what version of Ruby SASS that corresponds to.

Would csstyle still (mostly) work without the nesting features that rely on `#{&}`?

**Comment by geddski** [comment]
FYI this appears to be in progress https://github.com/sass/libsass/issues/548

**Comment by lenngren** [comment]
Any more news or status change regarding this issue? When can we use csstyle with libsass (without the ruby sass loader workaround)?
