### ISSUE TITLE
LESS Support

### ISSUE THREAD

**Issue by kentcdodds** [geddski/csstyle#2]
We use less at work and are getting ready to make an overhaul of our styles. With support for less, we may adopt the csstyle methodology.

**Comment by geddski** [comment]
I've just added support for [postcss](https://github.com/postcss/postcss) which is a fantastic processor. The tests are refactored to handle multiple implementations of csstyle without letting them get out of sync. If someone wants to submit a PR to support LESS and commits to maintaining the LESS version I'll be happy to merge.

**Comment by geddski** [comment]
closing this for now, see previous comment.
