### ISSUE TITLE
[Question] How to use this concept in the real life.

### ISSUE THREAD

**Issue by GesJeremie** [geddski/csstyle#20]
Hi :)

I'm really excited about your project and i think your concept is awesome (I imagined something like this 1 week ago after a huge customer project). 

Right now I use bootstrap or skeleton for grids and a plenty of third packages for javascript (slideshow, etc ...) and I have a question : 

- If I start to use this concept for my next project, I can forget bootstrap for grids and minimal UI because definitely it's not the same concept in mind. Imagine the mess into my HTML code. Btw I can use a grid on demand with Sass like Susy but ... what will happen for javascript plugins ? They use a lot of css code to run and i want keep a clean HTML, I don't want mix two concepts of CSS if you know what I mean. 

So, right now i'm fucking excited but I dunno how to start ... I hate you :p !

**Comment by geddski** [comment]
Yeah, it would be nice if every project out there used the same semantics right :) The best we can do when using multiple tools is keep the things we write separate from the things we depend on. So you can use csstyle for the CSS you write, and still leverage a third party grid or widget lib.
