### ISSUE TITLE
Allow Configuration Of Delimeters

### ISSUE THREAD

**Issue by Undistraction** [geddski/csstyle#22]
Please allow user-defined delimiters. For example I use a variation on BEM naming proposed by Nicholas Gallagher [here](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md).

This  means that component names are Pascal-case, subcomponent names are camel-case and all components are separated with a single `-` rather than a `__`. Being able to configure the delimiters you use would make this lib much more flexible. Simple namespaced variables would be great:

```
$cssstyle-component-delimeter: '__' !default;
```

**Comment by geddski** [comment]
added in 1.2.0. Thanks for the feedback y'all.
