### ISSUE TITLE
Hover/Active/Focus states

### ISSUE THREAD

**Issue by jacobdubail** [geddski/csstyle#24]
Great project! I'm using it for a new site right now.

Wondering what your prescribed approach is for handling pseudo class (states) for component parts:

```
@include component(figure) {
  ...
  @include part(caption) {
    ...
    opacity: 0;
  }

  &:hover .figure__caption {
    opacity: 1;
  }
}
```

That's the only way I can figure out to do it, but seems counter-productive.

Thanks!

**Comment by geddski** [comment]
Oh gotcha. Yeah that's lame having to write out the concatenated selector manually. Let me see if there's a better way.

**Comment by geddski** [comment]
Alright. So with sass you can move the `&` to the end of the selector and it will make it apply to the parent context. So a simple `:hover & {...}` will do the trick. Updated example, showing it working even with deeply nested parts: http://codepen.io/geddesign/pen/QwGErb

I should add this to the docs. Thanks!

**Comment by geddski** [comment]
I added an FAQ to the readme and included this.

**Comment by jacobdubail** [comment]
Thanks @geddski!

That's pretty close, but the hover selector is printed like this: :hover .capacitor__flux, which means when I hover the body (or any element) the capacitor_flux updates. That's not quite the intent. We're more interested in the following:

.component:hover .component__part { ... }

Whereas the proposed solution does this:

:hover .component__part { ... }

Thanks again,
Jacob

**Comment by geddski** [comment]
@jacobdubail third time's a charm :) Here's two ways to accomplish it: http://codepen.io/anon/pen/jEVBLw

Which do you like best and think we should recommend for people?

**Comment by geddski** [comment]
would be cool if I could expose a scoped `$component` variable as well...

**Comment by GabrielD42** [comment]
`.class:hover &` requires the use of a class. Both this issue as well as this entire project seem to be designed so that no classes will be directly referenced in the sass source. Therefore, I think `&:hover &` is the better choice.

Just my (unasked for) opinion. Take it or leave it.

**Comment by geddski** [comment]
fair point

**Comment by jacobdubail** [comment]
I agree with GabrielD42.  Avoiding typing the classname seems like a win.  Too bad there isn't a way to grab some kind of $parent variable or &parent or something so instead of:
.capacitor:hover & {
      background: blue;
    }
we could do:
&parent:hover & {
      background: blue;
    }

Let's consider this closed. Thanks for sticking with it!
