### ISSUE TITLE
 Conversion error #{&}

### ISSUE THREAD

**Issue by ckreutz** [geddski/csstyle#27]
Hello!

The concept looks awesome. Unfortunately I cannot make it work on either Rails or Jekyll, because there comes the following conversion error: 

  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/csstyle.scss':
  Invalid CSS after "...x: str-index(#{": expected expression (e.g. 1px, bold), was "&}, "__") - 1;" 

Any hint how that can be solved?

**Comment by geddski** [comment]
@ckreutz awesome, glad you like it :)
