### ISSUE TITLE
Simplify the syntax

### ISSUE THREAD

**Issue by niutech** [geddski/csstyle#29]
The syntax of class names is overcomplicated - there are too many symbols: `--`, `__`, `+`, `@`. This is definitely not KISS.

**Comment by geddski** [comment]
What do you suggest?

**Comment by niutech** [comment]
Just class names, e.g. `class="button action rounded glass"`, smilar to [OOCSS](https://github.com/stubbornella/oocss/wiki)

**Comment by geddski** [comment]
The symbols are what bring semantics to the markup. Otherwise how would you distinguish between a component and an option for example? 

That said, I am considering reworking or removing locations. Thanks for your input.

**Comment by geddski** [comment]
@niutech FYI you can now configure all the symbols to use whatever you want. :)
