### ISSUE TITLE
Postcss support 

### ISSUE THREAD

**Issue by bjrmatos** [geddski/csstyle#31]
I see csstyle plan to support rework #13 but dont start to work in it because rework not support nested styles.

I suggest to start with support for [postcss](https://github.com/postcss/postcss) that has support for nested styles with a [plugin](https://github.com/postcss/postcss-nested) and it has the same features (and more) that rework.

What do you think?

**Comment by geddski** [comment]
I'll take a look!

**Comment by geddski** [comment]
@bjrmatos this is looking promising. Should have something soon.

**Comment by geddski** [comment]
Great news! Postcss is now fully supported in csstyle 1.3.0. I find that I quite enjoy postcss and this was relatively easy and fun to implement.

**Comment by bjrmatos** [comment]
great news! finally i could leave sass and write modern css :D
