### ISSUE TITLE
Wrap options with media queries? Or the other way around?

### ISSUE THREAD

**Issue by ayatojhans** [geddski/csstyle#35]
This is not an actual issue, but I didn't find a place to discuss this.

Let's say I have a header component, and I'm using options to set the background image depending on the page. I also want to use a small or large version of the background image depending on the viewport resolution.

Option A
```sass
@include component(header) {
    // some styling

    @media all and (min-width: 320px) {
        @include option(contact){
            // set background image
        }
        @include option(about){
            // set background image
        }
    }
    @media all and (min-width: 768px) {
        @include option(contact){
            // set background image
        }
        @include option(about){
            // set background image
        }
    }
}
```

Option B
```sass
@include component(header) {
    // some styling

    @include option(contact){
        @media all and (min-width: 320px) {
            // set background image
        }
        @media all and (min-width: 768px) {
            // set background image
        }
    }

    @include option(about){
        @media all and (min-width: 320px) {
            // set background image
        }
        @media all and (min-width: 768px) {
            // set background image
        }
    }
}
```

Is there any difference at all?

**Comment by geddski** [comment]
I much prefer the readability of option B's syntax. It means when you're working on the `about` option it's all in one place. I'd also give your breakpoints variable names to make them more readable. The CSS that is generated is slightly less verbose with option A, but the rendering is identical. So it comes down to whichever syntax you prefer :)
