### ISSUE TITLE
Why is this plugin useful...?

### ISSUE THREAD

**Issue by kuerbi** [geddski/csstyle#53]
Can someone please explain me this?

Whats the difference between

```javascript
<style>
.button {
    background: #6BD9ED;
    padding: 15px;
}
</style>
<a class="button">Neat!</a>
```

and
```javascript
@include component(button) {
  background: #6BD9ED;
  padding: 15px;
}

<a class="button">Neat!</a>
```

why should I use compoment(name) instead of .classname.

and what does "generates your selectors for you" mean?

Thanks

**Comment by geddski** [comment]
Component mixin by itself isn't too valuable, just like the B in BEM doesn't do much on its own. It's when you start using options and parts and tweaks that csstyle really helps you write maintainable CSS.
