### ISSUE TITLE
csstyle.io links broken

### ISSUE THREAD

**Issue by filipnaumovic** [geddski/csstyle#63]
Hi,

seems all external links on the preview site are dead, console messages:

`Refused to display 'https://github.com/geddski/csstyle#getting-started' in a frame because it set 'X-Frame-Options' to 'deny'.`

**Comment by geddski** [comment]
Oh interesting. It looks like when I switched static site providers from divshot (dead now) to netlify, they wrap your site in an iframe. I'll get in touch with them to have them remove it. Thanks for the heads up!

**Comment by geddski** [comment]
Fixed now, thanks for the heads up @filipnaumovic. It was a DNS issue, causing the site to be wrapped in an iframe. Didn't know DNS could even do that. ¯\_(ツ)_/¯
